const BRANCH_LABELS = { "life-safety": "LIFE SAFETY", critical: "CRITICAL", equipment: "EQUIPMENT" };

export function AtsTransferReport({ report, system, company }) {
  const details = report.ats_details || [];
  return (
    <div className="report-doc">
      <div className="report-doc-header">
        <div className="report-doc-brand">{company?.logo_data ? <img src={company.logo_data} alt={`${company.name} logo`} /> : "CPC"}</div>
        <div className="report-doc-title-block">
          <div className="report-doc-command-title">CPC · Critical Power Command</div>
          <div className="report-doc-title">ATS Transfer Report</div>
          <div className="report-doc-subtitle">{system?.name || "—"} — {report.event_type || (report.type === "test" ? "Test" : "Emergency")} Event</div>
        </div>
        <div className="report-doc-date-block">
          <div className="report-doc-date-label">EVENT DATE</div>
          <div className="report-doc-date-value">{report.report_date}</div>
        </div>
      </div>

      <div className="report-doc-tiles">
        <div className="report-doc-tile dark"><div className="report-doc-tile-value">{details.length}</div><div className="report-doc-tile-label">ATS AFFECTED</div></div>
        <div className="report-doc-tile red"><div className="report-doc-tile-value">{report.duration_label || "—"}</div><div className="report-doc-tile-label">EVENT DURATION</div></div>
        <div className="report-doc-tile light"><div className="report-doc-tile-value dark-text">{report.initiating_ats || "—"}</div><div className="report-doc-tile-label light-label">INITIATING ATS</div></div>
        <div className="report-doc-tile light"><div className="report-doc-tile-value blue-text">{(report.event_type || (report.type === "test" ? "Test" : "Emergency")).toUpperCase()}</div><div className="report-doc-tile-label light-label">EVENT TYPE</div></div>
      </div>

      <div className="report-doc-section-title">ATS DETAILS</div>
      <div className="report-doc-ats-list">
        {details.map((d) => (
          <div className="report-doc-ats-card" key={d.ats_name}>
            <div className="report-doc-ats-card-top">
              <span className={`report-doc-branch-badge ${d.branch || "equipment"}`}>{BRANCH_LABELS[d.branch] || (d.branch || "").toUpperCase()}</span>
              <span className="report-doc-ats-name">{d.ats_name}</span>
              <div className="report-doc-ats-duration">
                <div className="report-doc-ats-duration-value">{d.on_emergency_duration || "—"}</div>
                <div className="report-doc-ats-duration-label">ON EMERGENCY</div>
              </div>
            </div>
            <div className="report-doc-ats-fields">
              <AtsField label="Manufacturer" value={d.manufacturer} link />
              <AtsField label="Serial Number" value={d.serial_number} link />
              <AtsField label="Switched to Emerg." value={d.switched_to_emergency} />
              <AtsField label="Switched to Normal" value={d.switched_to_normal} />
              <AtsField label="Time to Buss" value={d.time_to_bus_sec != null ? `${d.time_to_bus_sec} sec` : null} />
              <AtsField label="Time to Available" value={d.time_to_available_sec != null ? `${d.time_to_available_sec} sec` : null} />
            </div>
          </div>
        ))}
        {!details.length && <p className="report-doc-empty">No ATS units were recorded for this event.</p>}
      </div>

      <div className="report-doc-footer">
        <span>Generated by CPC · {company?.name || "—"} — {system?.name || "—"}</span>
        <span>{report.report_code} · Page 1 of 1</span>
      </div>
    </div>
  );
}

function AtsField({ label, value, link }) {
  return (
    <div className="report-doc-ats-field">
      <div className="report-doc-info-label">{label}</div>
      <div className={`report-doc-ats-field-value${link ? " link" : ""}`}>{value || "—"}</div>
    </div>
  );
}
