import { LoadProfileChart } from "../../components/chart/LoadProfileChart";

const fmt = (value, digits = 1) => (value == null ? "—" : Number(value).toFixed(digits));

export function GeneratorRunReport({ report, system, company }) {
  const log = report.telemetry_log || [];
  return (
    <div className="report-doc">
      <div className="report-doc-header">
        <div className="report-doc-brand">{company?.logo_data ? <img src={company.logo_data} alt={`${company.name} logo`} /> : "CPC"}</div>
        <div className="report-doc-title-block">
          <div className="report-doc-title">Generator Run Report</div>
          <div className="report-doc-subtitle">{system?.name || "—"} — {report.initiating_ats || "GEN"}</div>
        </div>
        <div className="report-doc-date-block">
          <div className="report-doc-date-label">RUN DATE</div>
          <div className="report-doc-date-value">{report.report_date}</div>
        </div>
      </div>

      <div className="report-doc-info-strip">
        <InfoCell label="MAKE" value={report.make} />
        <InfoCell label="MODEL" value={report.model} />
        <InfoCell label="SERIAL NUMBER" value={report.serial_number} />
        <InfoCell label="RATED KW" value={report.rated_kw ? `${report.rated_kw} kW` : null} />
        <InfoCell label="RATED VOLTAGE" value={report.rated_voltage ? `${report.rated_voltage} V` : null} />
        <InfoCell label="RATED AMPERAGE" value={report.rated_amperage ? `${report.rated_amperage} A` : null} />
      </div>

      <div className="report-doc-tiles">
        <div className="report-doc-tile dark"><div className="report-doc-tile-value">{fmt(report.start_hours, 2)}</div><div className="report-doc-tile-label">START HOURS</div></div>
        <div className="report-doc-tile dark"><div className="report-doc-tile-value">{fmt(report.end_hours, 2)}</div><div className="report-doc-tile-label">END HOURS</div></div>
        <div className="report-doc-tile red"><div className="report-doc-tile-value">{report.duration_label || "—"}</div><div className="report-doc-tile-label">TOTAL RUN TIME</div></div>
      </div>

      <div className="report-doc-section-title">POWER OUTPUT TREND</div>
      <div className="report-doc-chart-wrap">
        {(report.load_profile_data || []).length > 0 && (
          <LoadProfileChart
            loadProfile={report.load_profile_data}
            ratedKw={report.rated_kw || 0}
            peakKw={report.peak_kw || 0}
            durationMin={report.duration_min || 0}
          />
        )}
      </div>

      <div className="report-doc-section-title">TELEMETRY DATA LOG</div>
      <div className="report-doc-table-wrap">
        <table className="report-doc-table">
          <thead>
            <tr>
              <th>Time</th><th>V<sub>AB</sub></th><th>V<sub>BC</sub></th><th>V<sub>CA</sub></th>
              <th>A<sub>A</sub></th><th>A<sub>B</sub></th><th>A<sub>C</sub></th>
              <th>KW</th><th>%KW</th><th>Oil PSI</th><th>Water °F</th><th>Batt V</th><th>Hours</th>
            </tr>
          </thead>
          <tbody>
            {log.map((row, i) => (
              <tr key={i}>
                <td className="mono">{row.time}</td>
                <td>{row.vab ?? "—"}</td><td>{row.vbc ?? "—"}</td><td>{row.vca ?? "—"}</td>
                <td>{row.ia ?? "—"}</td><td>{row.ib ?? "—"}</td><td>{row.ic ?? "—"}</td>
                <td className="report-doc-cell-blue">{row.kw ?? "—"}</td>
                <td className="report-doc-cell-orange">{row.pct_kw ?? "—"}</td>
                <td>{row.oil_psi ?? "—"}</td><td>{row.water_temp_f ?? "—"}</td><td>{row.batt_v ?? "—"}</td>
                <td>{row.hours ?? "—"}</td>
              </tr>
            ))}
            {!log.length && <tr><td colSpan={13} className="report-doc-empty">No telemetry samples recorded for this run.</td></tr>}
          </tbody>
        </table>
      </div>

      <div className="report-doc-footer">
        <span>Generated by CPC · {company?.name || "—"} — {system?.name || "—"}</span>
        <span>{report.report_code} · Page 1 of 1</span>
      </div>
    </div>
  );
}

function InfoCell({ label, value }) {
  return (
    <div className="report-doc-info-cell">
      <div className="report-doc-info-label">{label}</div>
      <div className="report-doc-info-value">{value || "—"}</div>
    </div>
  );
}
