import { useMemo, useState } from "react";

import { usePageHeader } from "../../components/layout/HeaderContext";

const DASHBOARDS = [
  { uid: "empm-system-overview", label: "System overview", description: "Fleet health, active load, and generator utilisation." },
  { uid: "empm-generator-trends", label: "Generator performance", description: "Runtime and load trends across the selected period." },
  { uid: "empm-power-quality", label: "Power quality", description: "Voltage and frequency behaviour for early quality investigation." },
];

function grafanaBaseUrl() {
  return (import.meta.env.VITE_GRAFANA_URL || `http://${window.location.hostname}:3000`).replace(/\/$/, "");
}

export function Analytics() {
  usePageHeader("Analytics");
  const [selectedUid, setSelectedUid] = useState(DASHBOARDS[0].uid);
  const selected = DASHBOARDS.find((dashboard) => dashboard.uid === selectedUid) || DASHBOARDS[0];
  const dashboardUrl = useMemo(() => `${grafanaBaseUrl()}/d/${selected.uid}?orgId=1&kiosk`, [selected.uid]);

  return (
    <div>
      <section className="analytics-intro">
        <div>
          <h2>Grafana-powered telemetry analytics</h2>
          <p>
            Select a pre-built dashboard to explore its time range and visualisations. Administrators can open the full
            Grafana workspace to create and save their own dashboards.
          </p>
        </div>
        <button className="analytics-open-btn" onClick={() => window.open(dashboardUrl.replace("&kiosk", ""), "_blank", "noopener,noreferrer")}>
          Open in Grafana ↗
        </button>
      </section>

      <div className="analytics-tabs" aria-label="Analytics dashboards">
        {DASHBOARDS.map((dashboard) => (
          <button key={dashboard.uid} className={`analytics-tab${dashboard.uid === selected.uid ? " active" : ""}`} onClick={() => setSelectedUid(dashboard.uid)}>
            {dashboard.label}
          </button>
        ))}
      </div>

      <div className="analytics-frame-card">
        <div className="analytics-frame-note"><strong>{selected.label}:</strong> {selected.description} Demo data is generated by Grafana's TestData source.</div>
        <iframe className="analytics-frame" title={selected.label} src={dashboardUrl} />
      </div>
    </div>
  );
}
